export const OpType = {
    ADD_NOTE_RELATION: 'ADD_NOTE_RELATION',
    DELETE_NOTE_RELATION: 'DELETE_NOTE_RELATION',
    ASSOCIATE_A_NOTE: 'ASSOCIATE_A_NOTE',
    OPEN_EVERNOTE_LINK: 'OPEN_EVERNOTE_LINK'
}