version: "3.9"
services:
  backend: 
    build: backend
    ports: 
      - "5000:5001"
    environment:
      EVERNOTE_TOKEN: "${EVERNOTE_TOKEN}"
  frontend:
    build: frontend
    ports: 
      - "8080:8080"
    environment:
            # EVERNOTE_SERVER_HOST: "20.243.104.15"
      EVERNOTE_SERVER_HOST: "catwang.top"
      EVERNOTE_SERVER_PORT: "5000"
