version: "3.9.1"
services:
  backend: 
    build: backend
    ports: 
      - "5000:5001"
    environment:
      EVERNOTE_TOKEN: "${EVERNOTE_TOKEN}"
  frontend:
    build: frontend
    ports: 
      - "8080:8080"
    environment:
      EVERNOTE_API_ENDPOINT: "${EVERNOTE_API_ENDPOINT}"
  mysql:
    image: armv7/armhf-mysql:5.5.44
    volumes:
      - ./data/mysql/datadir:/var/lib/mysql
    ports: 
      - "3000:3000"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"