import { getEnv } from '../../utils/index'
import { ClientType } from './jupyter';

export const JUPYTER_BASE_URL = getEnv('REACT_APP_JUPYTER_BASE_URL');
export const JUPYTER_ROOT_FOLDER = getEnv('REACT_APP_JUPYTER_ROOT_FOLDER')
export const JUPYTER_CLIENT_TYPE = ClientType.fromString(getEnv('REACT_APP_JUPYTER_CLIENT_TYPE'))
export const JUPYTER_CLIENT_ENDPOINT = getEnv('REACT_APP_JUPYTER_CLIENT_ENDPOINT')

export const OpType = {
    ASSOCIATE_JUPYTER_NOTE: "ASSOCIATE_JUPYTER_NOTE",
    DELETE_ASSOCIATED_JUPYTER_NOTE: "DELETE_ASSOCIATED_JUPYTER_NOTE",
}

export const FocusMode = {
    REMOVING_JUPYTER_NOTEBOOK: "REMOVING_JUPYTER_NOTEBOOK",
    NOTIFY_REMOVED_JUPYTER_NOTEBOOK: "NOTIFY_REMOVED_JUPYTER_NOTEBOOK",
    CONFIRM_CREATE_JUPYTER_NOTEBOOK: "CONFIRM_CREATE_JUPYTER_NOTEBOOK",
    ASSOCIATE_JUPYTER_NOTEBOOK: "ASSOCIATE_JUPYTER_NOTEBOOK"
}